// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvtpomxznchyuimijtyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dHBvbXh6bmNoeXVpbWlqdHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODczNTgsImV4cCI6MjA3MzU2MzM1OH0.6JG3B7Sz99m2Fwy4sRhOsIJEFKz6xYDESMorf5qPNUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});